#!/usr/bin/env bash

# bump-version.sh - Update version in repository and create release branch
#
# Usage: ./scripts/bump-version.sh <version>
# Example: ./scripts/bump-version.sh v0.1.0
#
# This script:
# 1. Validates semantic version format
# 2. Checks for uncommitted changes (warns but allows override)
# 3. Updates go.mod with new version
# 4. Generates cmd/frozendb/version.go with version constant
# 5. Creates release branch (release/{version})
# 6. Commits changes
# 7. Pushes branch to remote

set -e  # Exit on any error

# Change to repository root (parent of scripts directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Error handling function
error() {
    echo -e "${RED}Error: $1${NC}" >&2
    exit 1
}

success() {
    echo -e "${GREEN}$1${NC}"
}

warning() {
    echo -e "${YELLOW}Warning: $1${NC}"
}

info() {
    echo "$1"
}

info "Working directory: $REPO_ROOT"

# Check if version argument provided
if [ $# -eq 0 ]; then
    error "No version specified\nUsage: $0 <version>\nExample: $0 v0.1.0"
fi

VERSION="$1"

# Validate semantic version format
info "Checking version format..."
VERSION_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$'

if ! [[ "$VERSION" =~ $VERSION_REGEX ]]; then
    error "Invalid version format '$VERSION'\nVersion must follow pattern: vMAJOR.MINOR.PATCH[-PRERELEASE]\nExamples: v0.1.0, v1.2.3, v2.0.0-rc1"
fi

success "Version format valid: $VERSION"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    error "Not in a git repository"
fi

# Check for uncommitted changes
info "Checking for uncommitted changes..."
# Check if HEAD exists (repo has commits)
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    if ! git diff-index --quiet HEAD -- 2>/dev/null; then
        warning "You have uncommitted changes in your working directory"
        warning "It's recommended to commit or stash them before bumping the version"
        echo ""
        echo "Uncommitted changes:"
        git status --short
        echo ""
        echo "Press Enter to continue anyway, or Ctrl+C to cancel"
        read -r
    else
        success "Working directory is clean"
    fi
else
    warning "Repository has no commits yet"
    info "Proceeding with version bump"
fi

# Get current branch (or create main if repo is new)
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    info "Current branch: $CURRENT_BRANCH"
else
    CURRENT_BRANCH="main"
    info "Initializing repository on branch: $CURRENT_BRANCH"
fi

# Check if release branch already exists
RELEASE_BRANCH="release/$VERSION"
if git show-ref --verify --quiet "refs/heads/$RELEASE_BRANCH"; then
    error "Branch '$RELEASE_BRANCH' already exists locally\nPlease check: git branch -a | grep $RELEASE_BRANCH"
fi

# Check if release branch exists on remote (only if origin exists)
if git remote get-url origin >/dev/null 2>&1; then
    if git ls-remote --heads origin "$RELEASE_BRANCH" 2>/dev/null | grep -q "$RELEASE_BRANCH"; then
        error "Branch '$RELEASE_BRANCH' already exists on remote\nPlease check: git branch -r | grep $RELEASE_BRANCH"
    fi
else
    info "No remote 'origin' configured (this is OK for local testing)"
fi

# Create release branch
info "Creating release branch: $RELEASE_BRANCH"
if ! git checkout -b "$RELEASE_BRANCH"; then
    error "Failed to create branch '$RELEASE_BRANCH'"
fi
success "Created branch: $RELEASE_BRANCH"

# Generate version.go file
VERSION_GO_PATH="cmd/frozendb/version.go"
info "Generating $VERSION_GO_PATH..."

# Create cmd/frozendb directory if it doesn't exist
mkdir -p "$(dirname "$VERSION_GO_PATH")"

# Write version.go file
cat > "$VERSION_GO_PATH" << EOF
// version.go - Generated by scripts/bump-version.sh
// DO NOT EDIT: This file is automatically generated
package main

const Version = "$VERSION"
EOF

if [ ! -f "$VERSION_GO_PATH" ]; then
    git checkout "$CURRENT_BRANCH"
    git branch -D "$RELEASE_BRANCH"
    error "Failed to generate $VERSION_GO_PATH\nBranch has been deleted to restore clean state"
fi
success "Generated $VERSION_GO_PATH"

# Stage changes
info "Staging changes..."
if ! git add "$VERSION_GO_PATH"; then
    git checkout "$CURRENT_BRANCH"
    git branch -D "$RELEASE_BRANCH"
    error "Failed to stage changes\nBranch has been deleted to restore clean state"
fi

# Commit changes
COMMIT_MESSAGE="Bump version to $VERSION"
info "Committing changes..."
if ! git commit -m "$COMMIT_MESSAGE"; then
    git checkout "$CURRENT_BRANCH"
    git branch -D "$RELEASE_BRANCH"
    error "Failed to commit changes\nBranch has been deleted to restore clean state"
fi
success "Committed: $COMMIT_MESSAGE"

# Push to remote (if remote exists)
if git remote get-url origin >/dev/null 2>&1; then
    info "Pushing to remote..."
    if ! git push -u origin "$RELEASE_BRANCH"; then
        warning "Failed to push to remote"
        warning "Local changes have been committed to: $RELEASE_BRANCH"
        warning "You can retry the push with: git push -u origin $RELEASE_BRANCH"
        exit 1
    fi
    success "Pushed branch to remote: $RELEASE_BRANCH"
else
    info "No remote 'origin' configured - skipping push"
    info "Branch created locally: $RELEASE_BRANCH"
fi

# Success message
echo ""
success "Successfully created release branch: $RELEASE_BRANCH"
echo ""
echo "Next steps:"
echo "  1. Create a pull request from $RELEASE_BRANCH to main"
echo "  2. Review and merge the PR"
echo "  3. Create a GitHub release from main with tag $VERSION"
echo "  4. Automated builds will attach binaries to the release"
echo ""
